// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMigration = "migrations"

// Migration mapped from table <migrations>
type Migration struct {
	Version int64 `gorm:"column:version;primaryKey" json:"version"`
	Dirty   bool  `gorm:"column:dirty;not null" json:"dirty"`
}

// TableName Migration's table name
func (*Migration) TableName() string {
	return TableNameMigration
}
